## Data-Driven Finance II<br>Rice University <br>Spring 2024


#### Instructor

[Kerry Back](http://kerryback.com)
<br>
J. Howard Creekmore Professor of Finance and Professor of Economics<br>
<a href="mailto:kerryback@gmail.com">kerryback@gmail.com</a>

#### Meeting Schedule

10:50 -- 12:05, 1/8/2024 -- 2/23/2024

#### Course Description

The first half of the course will be devoted to quantitative equity investing.  Quantitative equity investing is using quantifiable signals to select stocks via algorithms.  We'll explore machine learning methods to predict returns, backtest trading strategies based on the signals.  And, we will analyze the results in the way that endowments and other institutions evaluate investment managers.  We'll do a real-world implementation of our algorithms using daily updated company financials and market data and with paper trading via the python API at Alpaca Brokerage.

The second half of the course will be spent on options and futures.  Options and futures are important instruments for risk management and also for investing.  We'll explain what the securities are and how they trade, how they are used in risk management and investments, and how to value them.  

#### Assignments and Grading

Grades will be based on a group project, weekly assignments, and a final exam.  The group project will account for 20% of the course grade, the assignments for 40%, and the final exam for 40%.  Due dates for the assignments, exam, and project are as follows.  The final exam will cover only options and futures.  It will be distributed on Feb 22 and **due on Feb 27**.  The group project is **due April 23**.


#### Group project

Groups should consist of two or three students.  The project is to implement a 140/40 portfolio strategy at Alpaca brokerage, using their python API for paper trading.  The portfolio should be 100% long in SPY and 40% long-short with the longs and shorts based on return predictions from a machine learning model.  Each group should submit a pdf describing their investment strategy and an evaluation of their results.  The strategy should be **implemented by Friday, Feb 23**.  It should be rebalanced weekly, and results should be reported through **Friday, Apr 12**.  The write-up should include an analysis of the weekly returns relative to the weekly returns of SPY.  

#### Tentative Schedule

1. Factor investing
2. Backtesting momentum and value
3. Backtesting machine learning models
4. Strategy evaluation
5. Sector strategies
6. Alpaca API
7. Introduction to options
8. Risk management with options
9. Investing with options
10. Option valuation
11. Introduction to futures
12. Risk management with futures
13. Spot-futures parity
14. [Risk-management case](https://hbsp.harvard.edu/import/1121177)

#### Honor Code

The Rice University honor code applies to all work in this course.  Each student must do his or her own assignments, but it is allowed and in fact encouraged for students to seek advice from each other. 

#### Disability Accommodations

Any student with a documented disability requiring accommodations in this course is encouraged to
contact me outside of class. All discussions will remain confidential. Any adjustments or accommodations
regarding assignments or the final exam must be made in advance. Students with disabilities
should also contact Disability Support Services in the Allen Center.








